filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.keys_under_root: true
    json.add_error_key: true
    fields_under_root: true
    processors:
      - add_docker_metadata: ~

output.logstash:
  hosts: ["docker-elk-logstash-1:5044"]

